---
title: "Climate Change and Pollution Vulnerability in Oregon"
output:
  flexdashboard::flex_dashboard:
    theme:
      verson: 4
      bg: '#FFFFFF'
      fg: '#000000'
      primary: '#1A1A1A'
      navbar-bg: '#000000'
      base_font:
        google: Jost
      code_font:
        google: Noto Sans Mono
      heading_font:
        google: Jost
      font_scale: 1
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggiraph)
library(tigris)
library(sf)
library(biscale)
library(cowplot)
library(plotly)
library(shiny)

# Comments below are how to get from the CSV to the dataset needed for this prototype
# Only counties_sf, grouped_data, and metric_names are needed. The rest were removed before saving the .RData file.

federal_data <- read_csv("/Users/DL/Desktop/DATA510/1_0communities.csv")

oregon_data <-
  federal_data |>
  filter(`State/Territory` == "Oregon")

selected_data <-
  oregon_data |>
  select(-where(is.logical), -contains("percentile"))

metric_names <-
  selected_data |>
  as.data.frame() |>
  select(where(is.numeric)) |>
  names()

grouped_data <-
  selected_data |>
  group_by(`County Name`)

counties_sf <- counties(state = "OR", year = 2010)

rm(federal_data)
rm(oregon_data)
rm(selected_data)

save.image(file = "shiny_data.RData")

load("./shiny_data.RData")

```

Column {.sidebar data-width=320}
=====================================

### Select two metrics

```{r}
selectInput(inputId = "metric1",
            label = "Metric 1",
            choices = metric_names,
            selected = "PM2.5 in the air")

selectInput(inputId = "metric2",
            label = "Metric 2",
            choices = metric_names,
            selected = "Current asthma among adults aged greater than or equal to 18 years")
```

Map
=====================================

Row
-----------------------------------------------------------------------

### Vulnerability {.no-title}
```{r}
# Wanted this to be renderGirafe, but I was running into a graphics API version mismatch error with it

renderGirafe({
  counties_summary <-
    grouped_data |>
    summarize(metric1 = mean(.data[[input$metric1]], na.rm = T),
              metric2 = mean(.data[[input$metric2]], na.rm = T)) |>
    left_join(counties_sf, by = c("County Name" = "NAMELSAD10")) |>
    st_as_sf()
  
  counties_bivar <-
    counties_summary |>
    bi_class(x = metric1, y = metric2, style = "quantile", dim = 3)

  map <-
    ggplot(counties_bivar, aes(fill = bi_class,
                               tooltip = `County Name`)) +
    geom_sf_interactive() +
    bi_scale_fill(pal = "PurpleOr") +
    bi_theme() +
    theme(legend.position = "none",
          plot.margin = unit(c(0,4,0,0), "cm"))

  legend <-
    bi_legend(pal = "PurpleOr",
              dim = 3,
              xlab = input$metric1,
              ylab = input$metric2,
              size = 6)

  final_plot <- 
    ggdraw() +
    draw_plot(map, 0, 0.1, 1, 1) +
    draw_plot(legend, 0.7, 0.425, 0.35, 0.35)

  girafe(ggobj = final_plot)
  },
  
  outputArgs = list(width = 1386, height = 1188)
)


 
 #oregon_data[4:14]  =all of the demographic information

 #oregon_data[15:24] = totals and summary section of disadvantaged

 #oregon_data[15:24] = totals and summary section of disadvantaged

 #oregon_data[25:28] = totals and summary section of disadvantaged
                                                                                                                                    
 #oregon_data[25:28] = totals and summary section of disadvantaged


```

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
#columns 
