---
title: "oregon_climate_change"
author: "Ben Rubin"
date: "2023-06-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tigris)
library(sf)
library(biscale)
library(cowplot)
library(dplyr)
library(tibble)
library(DT)
```

## R Markdown

```{r}
federal_data <- read_csv("./1.0-communities.csv")

oregon_data <-
  federal_data |>
  filter(`State/Territory` == "Oregon")

tracts_sf <- tracts(state = "OR", year = 2010)

sf_w_data <- 
  left_join(oregon_data, tracts_sf, by = c("Census tract 2010 ID" = "GEOID10")) |>
  st_as_sf()
```


```{r}
counties_ver <-
  sf_w_data |>
  group_by(`County Name`) |>
  summarize(pm2.5  = mean(`PM2.5 in the air (percentile)`, na.rm = T),
            asthma = mean(`Current asthma among adults aged greater than or equal to 18 years (percentile)`, na.rm = T))

counties_bivar <-
  counties_ver |>
  bi_class(x = asthma, y = pm2.5, style = "quantile", dim = 3)


map <-
  ggplot(counties_bivar, aes(fill = bi_class)) +
  geom_sf() +
  bi_scale_fill(pal = "PurpleOr") +
  bi_theme() +
  theme(legend.position = "none",
        plot.margin = unit(c(0,14,0,0), "cm"))

legend <- 
  bi_legend(pal = "PurpleOr",
            dim = 3,
            xlab = "Higher rate of asthma",
            ylab = "Higher pm2.5 concentration",
            size = 14)

finalPlot <- ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +
  draw_plot(legend, 0.6, 0.26, 0.48, 0.48)

finalPlot
```


```{r}

```

```{r}
# comparing averages for each county to that of the state
oregon_num_only=oregon_data %>% select(`County Name`,`Census tract 2010 ID`,`State/Territory`) %>%  mutate(select_if(oregon_data, is.numeric))

oregon_num_only=replace(oregon_num_only,is.na(oregon_num_only),0) #na.rm or na.omit

oregon_num_counties=oregon_num_only %>% group_by(`County Name`) %>% summarise_if(is.numeric,mean,na.rm=T)
oregon_num_counties2=oregon_num_only %>% group_by(`County Name`) %>% summarise(population=sum(`Total population`))
oregon_num_counties=oregon_num_counties %>% 
                       ungroup %>% 
                       summarise(`County Name`=c(`County Name`, 'Oregon'),
                       across(where(is.numeric),~c(., mean(.))))

```

```{r}
county_compare=oregon_num_counties %>% 
  select(-matches("percentile")) %>% 
  select(-c(`Percentage of tract that is disadvantaged by area`, 
            `Share of neighbors that are identified as disadvantaged`,
            `Number of Tribal areas within Census tract for Alaska`,
            `Percent of residents who are not currently enrolled in higher ed`))
```

```{r}
county_compare=county_compare%>% select(c(1,10:26,29:33,36,39,42:47)) %>% select(-c(`Percentage households below 100% of federal poverty line in 2009 (island areas) and 2010 (states and PR)`,`Unemployment (percent) in 2009 (island areas) and 2010 (states and PR)`,`Percent of individuals below 200% Federal Poverty Line`,`Share of the tract's land area that is covered by impervious surface or cropland as a percent`,`Total categories exceeded`)) %>% 
  pivot_longer(!`County Name`,names_to="Index", values_to="value")
```

```{r}
# after we got things pivoted, we could make a new row and just call it Oregon state averages then divide across columns
Oregon_stats=county_compare %>% filter(`County Name`=="Oregon") %>% mutate(Oregon_values=value) %>% select(Index,Oregon_values)
county_compare=left_join(county_compare,Oregon_stats, by="Index") %>% mutate(ratio=(value-Oregon_values)/Oregon_values*100)


```


```{r}
county_compare %>%
  filter(`County Name`=="Union County") %>% 
  ggplot(aes(x=reorder(Index,ratio), y= ratio, fill=`County Name`))+
  geom_col(position = "dodge2")+
  coord_flip()+
  theme(legend.position = "none")+
  labs(x="variables", y="ratio for County vs State
       ")
```

```{r}

```


```{r}

oregon_num_counties2 %>% 
  ggplot(aes(x=reorder(`County Name`,`population`),y=`population`,fill=`County Name`))+
  geom_col()+
  coord_flip()+
  theme(legend.position = "none")+
  labs(x="Counties")

```

```{r}
oregon_num_counties
```

```{r}
DT::datatable(oregon_data) 
```

```{r}
features_list=unique(county_compare$Index)


```

#Percentile analysis
```{r}
#creating the vulneribility score for counties

county_compare2=oregon_num_counties %>% 
  select(matches("percentile")) %>% 
  select(matches(c("prox","burden","pm","100", 
                                 "unemployment", "flood", "fire", 
                                 "population", "agricultural", "building"))) %>%
  select(-`Traffic proximity and volume (percentile)`) %>% 
  mutate(vulnerability_score=rowSums(across(everything())))

county_compare2$`County Name`=oregon_num_counties$`County Name`

county_compare2=county_compare2 %>% 
  relocate(`County Name`, .before = `Proximity to hazardous waste sites (percentile)`) %>% 
  filter(`County Name`!="Oregon")
county_compare2

oregon_num_counties %>% select(matches("percentile"))
```




```{r}

county_compare3=oregon_num_counties %>% 
  select(-matches(c("percentile","states and PR"))) %>% 
  select(-c(`Total population`,`Percentage of tract that is disadvantaged by area`, 
            `Share of neighbors that are identified as disadvantaged`,
            `Number of Tribal areas within Census tract for Alaska`,
            `Percent of residents who are not currently enrolled in higher ed`,`County Name`,`Traffic proximity and volume`)) %>% 
  select(matches(c("prox","burden","100", 
                                 "unemployment", "flood", "fire", 
                                 "population", "agricultural", "building")))

county_compare3$`County Name`=oregon_num_counties$`County Name`

county_compare3=county_compare3 %>% 
  relocate(`County Name`, .before = `Proximity to hazardous waste sites`) %>% 
  filter(`County Name`!="Oregon")



county_compare3
```


```{r}
# get new percentiles for our features
percentile=function(x){
  r=(rank(x)-1)/(sum(!is.na(x))-1)*100
  return(r)
}

county_compare3[,paste0(names(county_compare3),"_pr")]=apply(county_compare3,2,percentile)

county_compare3=county_compare3[,-14]
```

```{r}


county_compare3$vulnerability_score=rowSums(county_compare3[,14:25])

county_compare3

```

```{r}
county_compare2 %>% 
  ggplot(aes(x=reorder(`County Name`,vulnerability_score),y=vulnerability_score))+
  geom_col(aes(fill=vulnerability_score))+
  coord_flip()+
  theme(legend.position="right")+
  labs(x="County Name",y="Vulnerability score", title= "vulnerability National percentiles")+
  scale_fill_gradient(low="blue", high="red")
  
county_compare3 %>% 
  ggplot(aes(x=reorder(`County Name`,vulnerability_score),y=vulnerability_score))+
  geom_col(aes(fill=vulnerability_score))+
  coord_flip()+
  theme(legend.position="right")+
  labs(x="County Name",y="Vulnerability score",title = "Vulnerability Oregon percentiles")+
  scale_fill_gradient(low="blue", high="red")
  

```
```{r}
write.csv(county_compare3,"./Oregon_county_vulnerability.csv",row.names=FALSE)
```

