---
title: "Climate Change Vulnerability in Oregon"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(dplyr)
library(stringr)
library(sf)
library(biscale)
library(cowplot)
library(ggiraph)
library(patchwork)
library(DT)
library(tidyr)
```

```{r global, include=FALSE}
load("../data/shiny_data.RData")

layout1 <- "
#######################
##BBBB#################
##BBBB##AAAAAAAAAAAAAAA
##BBBB##AAAAAAAAAAAAAAA
##BBBB##AAAAAAAAAAAAAAA
CCCCCCCCAAAAAAAAAAAAAAA
CCCCCCCCAAAAAAAAAAAAAAA
CCCCCCCCAAAAAAAAAAAAAAA
CCCCCCCCAAAAAAAAAAAAAAA
CCCCCCCCAAAAAAAAAAAAAAA
CCCCCCCCAAAAAAAAAAAAAAA
CCCCCCCC###############
#######################
"

layout2 <-"
#A
BA
BA
BA
#A
"

sens_options <- c(sens_options, demo_options)
```

Demand Action!
=====================================
```{r}
h4("Take a look at the other pages of this app to get an idea of what 
                 your community's most severe vulnerabilities are...", align = "center")
              h4("then follow these instructions to take action towards solving them!" ,
                 align = "center")
              br()
              p(h5("1. Find your state and/or US representative or legislator."))
              p("The following link takes you to a page that will help you to find your state and US
              representative or legislator. Once you've found this, save their contact information as it will be
              important later. These individuals can be 
              reached via email or mail, and both strategies are equally effective.")
              #br(),
              tags$a(href="https://geo.maps.arcgis.com/apps/instant/lookup/index.html?appid=fd070b56c975456ea2a25f7e3f4289d1", 
                     "Link to find your representitive and/or legislator")
              
              br("")
              
              br("")
              p(h5("2. Formulate your letter to your representative. "))
              p("The American Psychological Association's (APA) website offers a sample letter or email that can
                be used as a template (link below). Regardless of whether you use the autogenerated
                letter or not, it's imperative to state your communities specific risk, and highlight the urgent
                need for action.")
              tags$a(href="https://www.apa.org/advocacy/guide/sample-letters.pdf",
                     "Sample letter")
              
              br()
              tags$a(href="https://www.apa.org/advocacy/guide/sample-email.pdf", 
                     "Sample email")
              br()
              downloadButton('download',"Download our letter")
              
              br("")
              
              p(h5("3. Send your letter via email or mail to your representative"))
              p("According to the APA's guide on sending letters to a representative (link below), once the
                correspondence has been received a legislative correspondent verifies the identity of the sender
                to ensure they're a constituent, and then it is either routed or tallied. It may take some time
                to receive a response, and the guide goes on to explain that moving messages are shared with the
                representative directly.")
              tags$a(href="https://www.apa.org/advocacy/guide/letter-email", 
                     "Link to guide")
              
              br("")
              p(h5("4. While waiting for response, share this tool"))
              p("Share this tool to family, friends, and on social media to ensure that your representative
                understands the importance and urgency of this issue. ")
```

Vulnerability
===================================== 

Sidebar {.sidebar data-width=320}
-----------------------------------------------------------------------

### Select metrics

```{r}
selectInput(inputId = "sensitivity",
            label = "Sensitivity",
            choices = sens_options,
            selected = "Percent Black or African American alone")

selectInput(inputId = "exposure",
            label = "Exposure",
            choices = expo_options,
            selected = "Diesel particulate matter exposure")

# selectInput(inputId = "demographic",
#             label = "Racial group",
#             choices = demo_options,
#             selected = "Percent White")
```

Preset comparisons

```{r}
actionButton(inputId = "preset1",
             label = "Black population and diesel particulates")
```

<br />

```{r}
actionButton(inputId = "preset2",
             label = "Children and PM2.5 pollution")
```

<br />

```{r}
actionButton(inputId = "preset3",
             label = "Linguistic isolation and wildfires")
```

<br />

Column {.tabset}
-----------------------------------------------------------------------

### Sensitivity and Exposure
```{r}
observeEvent(input$preset2, {
  updateSelectInput(inputId = "sensitivity", selected = "Percent age under 10")
  updateSelectInput(inputId = "exposure", selected = "PM2.5 in the air")
#  updateSelectInput(inputId = "demographic", selected = "Percent White")
})

observeEvent(input$preset1, {
  updateSelectInput(inputId = "sensitivity", selected = "Percent Black or African American alone")
  updateSelectInput(inputId = "exposure", selected = "Diesel particulate matter exposure")
#  updateSelectInput(inputId = "demographic", selected = "Percent American Indian / Alaska Native")
})

observeEvent(input$preset3, {
  updateSelectInput(inputId = "sensitivity", selected = "Linguistic isolation (percent)")
  updateSelectInput(inputId = "exposure", selected = "Share of properties at risk of fire in 30 years")
#  updateSelectInput(inputId = "demographic", selected = "Percent Hispanic or Latino")
})

renderGirafe({
  counties_summary <-
    grouped_data |>
    summarize(sens = weighted.mean(.data[[input$sensitivity]], `Total population`, na.rm = T),
              expo = ifelse(str_detect(input$exposure, "rate|Share"),
                            weighted.mean(.data[[input$exposure]], `Total population`, na.rm = T),
                            mean(.data[[input$exposure]], na.rm = TRUE))) |> #,
              # demo = weighted.mean(.data[[input$demographic]], `Total population`, na.rm = T)) |>
    # mutate(scl1 = (sens - min(.data[["sens"]])) / (max(.data[["sens"]]) - min(.data[["sens"]])),
    #        scl2 = (expo - min(.data[["expo"]])) / (max(.data[["expo"]]) - min(.data[["expo"]])),
    #        vuln = (scl1 + scl2) / 2) |>
    left_join(counties_sf, by = c("County Name" = "NAMELSAD10")) |>
    st_as_sf()
  
  counties_bivar <-
    counties_summary |>
    bi_class(x = sens, 
             y = expo, 
             style = "quantile", 
             dim = 3)

  breaks <-
    counties_summary |>
    bi_class_breaks(x = sens,
                    y = expo, 
                    style = "quantile", 
                    dim = 3, 
                    split = TRUE)
  
  map <-
    counties_bivar |>
    ggplot(aes(fill = bi_class,
               tooltip = paste0(`County Name`, 
                                "\n", input$sensitivity, ": ", sens,
                                "\n", input$exposure, ": ", expo),
               data_id = `County Name`)) +
    geom_sf_interactive() +
    bi_scale_fill(pal = "PurpleOr") +
    bi_theme() +
    theme(legend.position = "none")
  
  scatter <-
    counties_bivar |>
    ggplot(aes(x = sens,
               y = expo,
               color = bi_class,
               tooltip = paste0(`County Name`, 
                                #"\n", input$demographic, ": ", demo,                                
                                "\n", input$sensitivity, ": ", sens,
                                "\n", input$exposure, ": ", expo))) +
    geom_point_interactive(alpha = 0.8,
                           size = 3) +
    bi_scale_color(pal = "PurpleOr") +
    labs(x = input$sensitivity, 
         y = input$exposure) +
    theme_minimal() +
    theme(legend.position = "none")
  
  legend <-
    bi_legend(pal = "PurpleOr",
              dim = 3,
              xlab = "Sensitivity",
              ylab = "Exposure",
              size = 10,
              breaks = breaks)

  girafe(ggobj = scatter + legend + map + plot_layout(design = layout1), 
         width_svg = 11.5, 
         height_svg = 6.5,
         options = list(
           opts_selection(
             type = "single")
           )
         )
  },
  
  outputArgs = list(width = 1150, height = 650)
)
```

### Overall vulnerability

```{r}

renderGirafe({
  
  counties_summary <-
    county_compare3 |>
    left_join(counties_sf, by = c("County Name" = "NAMELSAD10")) |>
    st_as_sf()
  
  map <-
    counties_summary |>
    ggplot(aes(fill = vulnerability_score,
               tooltip = paste0(`County Name`, "\n", vulnerability_score))) +
    geom_sf_interactive() +
    scale_fill_gradient(low="blue", high="red") +
    theme_minimal() +
    theme(legend.position = "top",
          panel.grid = element_blank(),
          axis.text = element_blank())
  
  bar <- 
    counties_summary |>
    ggplot(aes(x=reorder(`County Name`,vulnerability_score),y=vulnerability_score))+
    geom_col_interactive(aes(fill=vulnerability_score,
                             tooltip = vulnerability_score))+
    coord_flip()+
    theme(legend.position="none")+
    labs(x="County Name",y="Vulnerability score",title = "Vulnerability Oregon percentiles")+
    scale_fill_gradient(low="blue", high="red")

  girafe(ggobj = bar + map + plot_layout(design = layout2), 
         width_svg = 11.375, 
         height_svg = 6.5,
         options = list(
           opts_selection(
             type = "single")
           )
         )
  },
  
  outputArgs = list(width = 1150, height = 650)
)
```

County Snapshot
=====================================

Sidebar {.sidebar data-width=320}
-----------------------------------------------------------------------

```{r}
thedata <- reactive(oregon_data %>% select(input$show_vars) %>% filter(`County Name`== c(input$county)))

output$downloadData <- downloadHandler(
        filename = function(){"Oregon_snapshot_table.csv"}, 
        content = function(fname){
          write.csv(thedata(), fname)})

downloadLink('downloadData', 'Download the table') 

thedata2 = reactive(county_compare %>% filter(`County Name`== c(input$county)))
output$downloadData2= downloadHandler(
        filename=function(){"Oregon_snapshot_graph.csv"},
        content=function(fname){
          write.csv(thedata2(), fname)})

downloadLink('downloadData2', ' Download the graph')

selectInput(
            "county",
            "Select a County",
            c("All", sort(unique(
              as.character(oregon_data$`County Name`)
            ))), selected = "Baker County", multiple=T,
            )

tags$div(style="height: 750px; overflow-y:auto;",
                       checkboxGroupInput("show_vars", "Columns in the dataset to show:",
                                 names(oregon_data),selected= "County Name" ))
```

Column
-----------------------------------------------------------------------

### Vulnerability Graph

```{r, fig.height=7}
renderPlot({
        
        
      f=county_compare %>% 
          filter(`County Name` %in% c(input$county)) %>% 
          ggplot(aes(x=reorder(Index,ratio), y= ratio, fill=`County Name`))+
          geom_col(position = "dodge2")+
          coord_flip()+
          theme(legend.position = "right")+
          labs(x="Variables", y="Percent Difference from the State Average (%)")#+
          #scale_y_continuous(breaks=seq(0,220,40),limits=c(0,220))
        
      f 
        
        
    })
```

### County Information Table

```{r}
DT::renderDataTable({
        DT::datatable(oregon_data %>% select(input$show_vars) %>% filter(`County Name`%in% input$county))               
        
        # original filtering without piping -- ignore -> oregon_data[,input$show_vars , drop = FALSE])
        
      })
```

Single Metric
=====================================

Sidebar {.sidebar data-width=320}
-----------------------------------------------------------------------

```{r}
selectInput(inputId = "metric",
            label = "Metric",
            choices = single_val,
            selected = "Percent age under 10")
SIlayout <- "
AAAAAAAA#########
AAAAAAAA#########
AAAAAAAABBBBBBBBB
AAAAAAAABBBBBBBBB
AAAAAAAABBBBBBBBB
AAAAAAAABBBBBBBBB
AAAAAAAABBBBBBBBB
AAAAAAAABBBBBBBBB
#################
CCCCCCCC#DDDDDDDD
CCCCCCCC#DDDDDDDD
CCCCCCCC#DDDDDDDD
CCCCCCCC#DDDDDDDD
CCCCCCCC#DDDDDDDD
CCCCCCCC#DDDDDDDD
"
pal <- c("#00FF00", "#FFFF00", "#FF8C00", "#FF0000") 
```

Column
-----------------------------------------------------------------------

```{r}
renderGirafe({
  sel_data <-
    grouped_data |>
    summarize(metric = weighted.mean(.data[[input$metric]], `Total population`, na.rm = TRUE))%>%
    mutate(`County Name` = gsub(" County", "", `County Name`))%>%
    select(`County Name`,metric)%>%
    mutate(across(where(is.numeric), round, 3))
  
  
  avgline<-mean(sel_data$metric) #average
  
  coln=input$metric #metric name so I don't need to type stuff out every time
  

  
  
  
  #plot that compares metric by county
  county_bar<-sel_data |>
  ggplot(aes(x = metric, y = reorder(`County Name`,metric),
             tooltip= paste0(`County Name`,
                            "\n", coln,': ', metric)))+
    geom_bar_interactive(stat='identity',fill='lightgray',color='black')+ 
    ylab('County')+
    xlab(coln)+
    ggtitle(paste0(coln,' By County'))+

    geom_vline(xintercept = avgline, linetype = "dashed",lwd = .8)+
    theme_minimal()+
    theme(axis.title.x = element_text(face = "bold"))+
    theme(axis.title.y = element_text(face = "bold"))+
    theme(plot.title = element_text(face = "bold"))+
    theme(text = element_text(size = 18))
  
  
  blgh_data <- #data grouped for destroyed building hazard
    grouped_data |> mutate(
    bin = cut(`Expected building loss rate (Natural Hazards Risk Index) (percentile)`, breaks = c(0, 10, 50, 90, 100), labels = c("0-10th Percentile", "10-50th Percentile", "50-90th Percentile", "90-100th Percentile")))%>%
    group_by(bin)%>%
   summarize(metric = weighted.mean(.data[[input$metric]], `Total population`, na.rm = TRUE))%>%
   na.omit()%>%
    mutate(across(where(is.numeric), round, 3))
  
  
  blgh <- blgh_data |>
    ggplot(aes(x=bin, y=metric,fill=bin,
              tooltip= paste0(bin,
                            "\n", coln,': ', metric)))+
    geom_bar_interactive(stat='identity',color='black')+
    scale_fill_manual(values = pal)+
    geom_hline(yintercept = avgline, linetype = "dashed",lwd = .8)+
    xlab("Building Loss Due to Natural Hazards Nationwide Percentile")+
    ylab(coln)+
    ggtitle(paste0(coln,' in tracts \n',
                   'Organized by Risk of Building \nLoss Due to Natural Hazards'))+

    
    theme_minimal()+
    theme(axis.title.x = element_text(face = "bold"),
          axis.title.y = element_text(face = "bold"),
          plot.title = element_text(face = "bold"))+
    theme(text = element_text(size = 18),axis.text.x=element_blank(),
          legend.title = element_blank())


  
  haz_data <- #data grouped for proximity to hazardous waste
    grouped_data |> mutate(
    bin = cut(`Proximity to hazardous waste sites (percentile)`, breaks = c(0, 10, 50, 90, 100), labels = c("0-10th Percentile", "10-50th Percentile", "50-90th Percentile", "90-100th Percentile")))%>%
    group_by(bin)%>%
   summarize(metric = weighted.mean(.data[[input$metric]], `Total population`, na.rm = TRUE))%>%
   na.omit()%>%
    mutate(across(where(is.numeric), round, 3))
  
  
  haz <- haz_data |>
    ggplot(aes(x=bin, y=metric,fill=bin,
              tooltip= paste0(bin,
                            "\n", coln,': ', metric)))+
    geom_bar_interactive(stat='identity',color='black')+
    scale_fill_manual(values = pal)+
    geom_hline(yintercept = avgline, linetype = "dashed",lwd = .8)+
    xlab("Proximity to Hazardous Waste Facilities Nationwide Percentile")+
    ylab(coln)+
    ggtitle(paste0(coln,' in tracts \n',
                   'Organized by Proximity to \nHazardous Waste Facilities'))+

    
    theme_minimal()+
    theme(axis.title.x = element_text(face = "bold"),
          axis.title.y = element_blank(),
          plot.title = element_text(face = "bold"))+
    theme(text = element_text(size = 18),axis.text.x=element_blank(),
          legend.position="none")
  
    dpm_data <- #data grouped for diesel particulate matter in the air
    grouped_data |> mutate(
    bin = cut(`Diesel particulate matter exposure (percentile)`, breaks = c(0, 10, 50, 90, 100), labels = c("0-10th Percentile", "10-50th Percentile", "50-90th Percentile", "90-100th Percentile")))%>%
    group_by(bin)%>%
   summarize(metric = weighted.mean(.data[[input$metric]], `Total population`, na.rm = TRUE))%>%
   na.omit()%>%
      mutate(across(where(is.numeric), round, 3))
  
  
  dpm <- dpm_data |>
    ggplot(aes(x=bin, y=metric,fill=bin,
              tooltip= paste0(bin,
                            "\n", coln,': ', metric)))+
    geom_bar_interactive(stat='identity',color='black')+
    scale_fill_manual(values = pal)+
    geom_hline(yintercept = avgline, linetype = "dashed",lwd = .8)+
    xlab("Exposure to Diesel Particulate Matter Nationwide Percentile")+
    ylab(coln)+
    ggtitle(paste0(coln,' in tracts \n',
                   'Organized by Exposure to Diesel \nParticulate Matter'))+

    
    theme_minimal()+
    theme(axis.title.x = element_text(face = "bold"),
          axis.title.y = element_blank(),
          plot.title = element_text(face = "bold"))+
    theme(text = element_text(size = 18),
          axis.text.x=element_blank(),legend.position="none")
  
  
  
 girafe(ggobj = county_bar + blgh + haz + dpm + plot_layout(design = SIlayout), 
         width_svg = 20, 
         height_svg = 15,
         options = list(
           opts_selection(
             type = "single")
           )
         )
  
},
  outputArgs = list(width = 1000, height = 750)

)
```
